#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "comentario"
name = "Comentario"
description.en = "Embeddable web comment engine"
description.fr = "Moteur de commentaires web intégrable"

version = "3.17.0~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "MIT"
website = "https://comentario.app"
demo = "https://demo.comentario.app"
admindoc = "https://docs.comentario.app"
code = "https://gitlab.com/comentario/comentario"

fund = "https://yktoo.com/en/about/#donate"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "false" 
sso = "false"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://gitlab.com/api/v4/projects/42486427/packages/generic/comentario/3.17.0/comentario_3.17.0_linux_amd64.tar.gz"
        amd64.sha256 = "83e1fae5b6dda01659a13fff98e65d705b85a9e7c9cae21942b04127777ee4d7"
        arm64.url = "https://gitlab.com/api/v4/projects/42486427/packages/generic/comentario/3.17.0/comentario_3.17.0_linux_arm64.tar.gz"
        arm64.sha256 = "37ca102b47b9f2049c79b93882bd67f2fa0a9dab94f9a2ac4e739a460c8bcfb5"

        autoupdate.strategy = "latest_gitlab_release"
        autoupdate.asset.amd64 = "comentario_.*_amd64.tar.gz"
        autoupdate.asset.arm64 = "comentario_.*_arm64.tar.gz"

    [resources.system_user]
    allow_email = "true"
    mail_user = "no-reply"

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.database]
    type = "postgresql"
