# The static configuration environment for the Comentario backend
# Refer to the docs for details: https://docs.comentario.app/en/configuration/backend/static/

HOST=localhost
PORT=__PORT__
BASE_URL=https://__DOMAIN__:__PORT__
STATIC_PATH=__INSTALL_DIR__/frontend
SECRETS_FILE=__INSTALL_DIR__/secrets.yaml
SUPERUSER=__APP__@__DOMAIN__
MAX_IMPORT_FILE_SIZE=10MiB
STATS_DISABLE_PAGE_VIEWS=false
STATS_MAX_DAYS=30

