#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

mail_user="no-reply"
ynh_app_setting_set --key="mail_user" --value="$mail_user"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

pushd "$install_dir"
    mkdir -p backend
    mv -f comentario backend/comentario
    rm -r etc/
    find . -maxdepth 1 -type f -delete #remove remaining files in current folders (*.md, LICENSE)
popd

chown -R $app:www-data "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="comentario.conf" --destination="$install_dir/backend/comentario.conf"
ynh_config_add --template="secrets.yaml" --destination="$install_dir/backend/secrets.yaml"

chown -R $app:$app "$install_dir/backend"
chmod 600 "$install_dir/backend/comentario.conf"
chmod 400 "$install_dir/backend/secrets.yaml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --description="Comments engine app" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
